---
priorities:
    -   [ proc {|p| p > 3 }, 31;1 ]
    -   [ proc {|p| p > 1 }, 33;1 ]
    -   [ proc {|p| p < -7}, 0;35;2 ]
    -   [ proc {|p| p < 0 }, 0;37 ]

patterns:
    -   pattern:    /^[^x]*[^.]?(T:)/
        display:      31;1;7
        point:      3
    -   pattern:    /^[^x]*[^.]?(G:|D:)/
        display:      33;1;7
        point:      -5
    -   pattern:    /^\(A\)/
        point:      3
    -   pattern:    /^\(B\)/
        point:      2
    -   pattern:    /^\(C\)/
        point:      1
    -   pattern:    '/^x /'
        point:      -10
    -   pattern:    '/^(\+[^ ]+)/'
        display:      35;1;7
        point:      0.5
    -   pattern:    '/ (\+[^ ]+)/'
        display:      35;1;7
        point:      0.5
    -   pattern:    '/^[^x].*(WAIT) */'
        display:      36;7
        point:      -3
    -   pattern:    '/ (\d{4}-\d{2}-\d{2}) */'
        display:    proc {|match| %Q{\e[33m(#{relative_date(Date.parse match)})\e[m} }
    -   pattern:    '/^(@[^ ]+)/'
        display:      32;1
    -   pattern:    '/ (@[^ ]+)/'
        display:      32;1
    -   pattern:    '/^[^x].*(SOMEDAY|MAYBE) */'
        display:      36;7
        point:      -7

    -   pattern:    /\+neo /
        point:      0.3
    -   pattern:    /\+rpq/
        point:      3
